#!/bin/bash

# Exit on error
set -o errexit
# Exit on undefined variable
set -o nounset

# Wait for PostgreSQL to be ready
postgres_ready() {
python << END
import sys
import psycopg2
from urllib.parse import urlparse

try:
    # Parse DATABASE_URL or use individual env vars
    if 'DATABASE_URL' in dict(locals()):
        import os
        db_url = os.environ.get('DATABASE_URL', '')
        if db_url:
            result = urlparse(db_url)
            username = result.username
            password = result.password
            database = result.path[1:]
            hostname = result.hostname
            port = result.port
        else:
            username = os.environ.get('POSTGRES_USER', 'postgres')
            password = os.environ.get('POSTGRES_PASSWORD', '')
            database = os.environ.get('POSTGRES_DB', 'postgres')
            hostname = os.environ.get('POSTGRES_HOST', 'postgres')
            port = os.environ.get('POSTGRES_PORT', '5432')
    else:
        import os
        username = os.environ.get('POSTGRES_USER', 'postgres')
        password = os.environ.get('POSTGRES_PASSWORD', '')
        database = os.environ.get('POSTGRES_DB', 'postgres')
        hostname = os.environ.get('POSTGRES_HOST', 'postgres')
        port = os.environ.get('POSTGRES_PORT', '5432')

    conn = psycopg2.connect(
        dbname=database,
        user=username,
        password=password,
        host=hostname,
        port=port
    )
    conn.close()
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)
END
}

until postgres_ready; do
  echo 'Waiting for PostgreSQL to become available...'
  sleep 1
done
echo 'PostgreSQL is available'

exec "$@"
